config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'rules#index'

  resources :rules, only: [:index, :show, :search] do
    get 'search', on: :collection
  end

  resources :websites

end

app/models/feat.rb
class Feat < Rule
end

app/models/prerequisite.rb
class Prerequisite #< ActiveRecord::Base
  CLASSES = ["ardent", "artificer", "assasin", "avenger", "barbarian", "bard", "battlemind", "berserker", "cleric", \
    "fighter", "invoker", "monk", "paladin", "psion", "ranger", "rogue", "runepriest", "seeker", "shaman", \
    "sorcerer", "swordmage", "warden", "warlock", "warlord", "wizard", "vampire", "druid", "hunter", "scout"]

  POWER_SOURCES = { "divine"  => ["avenger", "cleric", "paladin", "invoker", "runepriest"],
                    "martial" => ["berserker", "bard", "fighter", "ranger", "rogue", "warlord"],
                    "primal"  => ["barbarian", "druid", "hunter", "scout", "seeker", "shaman", "warden"],
                    "arcane"  => ["artificer", "bard", "sorcerer", "swordmage", "warlock", "wizard"],
                    "psionic" => ["ardent", "battlemind", "monk", "psion"],
                    "shadow"  => ["assasin", "vampire"] }

  RACES = ["bladling", "changeling", "deva", "dragonborn", "drow", "dwarf", "eladrin", "elf", "genasi", \
    "githzerai", "gnome", "goliath", "half-elf", "half-orc", "halfling", "hamadryad", "hengeyokai", \
    "human", "kalashtar", "kenku", "minotaur", "mul", "pixie", "revenant", "satyr", "shade", "shardmind", \
    "shifter", "thri-kreen", "tiefling", "vryloka", "warforged", "wilden"]

  ATTRIBUTES = [ "str", "con", "dex", "int", "wis", "cha", "strenght", "constitution", "dexterity", \
    "intelligence", "wisdom", "charisma" ]


end

app/models/rule.rb
class Rule < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_content, :against => :content

  has_many :prerequisites

  def self.search(search_params)
    if search_params.blank?
      @rules = Rule.first(10)
    else
      @rules = Rule.search_by_content(search_params)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index
    @rules = Rule.search(params[:search])
    respond_to do |format|
      format.html { @rules }
      format.json { render json: @rules }
    end
  end

  def show
    @rule = Rule.find(params[:id])
    render json: @rule
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rule_helper.rb
module RuleHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %title D&D 4e Compendium
    = Gon::Base.render_data
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:name => "viewport", :content => "width = device-width, initial-scale = 1.0"}
  %body
    .container
      %h1 Welcome to Compendium!
      = yield

app/views/rules/%%_js_templates.html.haml
%script#template-rule-row{type: "text/x-handlebars-template"}
  %tr{id: "{{id}}", onclick: "show_content(this);"}
    %td {{name}}
    %td {{data.PrintPrereq}}
    %td {{data.ShortDescription}}

app/views/rules/_search.html.haml
.form-group#search_form
  = form_tag rules_path, method: 'get' do
    %label#search_label Find feats:
    = text_field_tag :search, params[:search], class: "form-control input"
    = submit_tag "Search", name: nil, class: "form-control btn btn-default", type: "button"

app/views/rules/index.html.haml
= render "search"
.row
  %div{class: "col-md-9"}
    <!-- Table -->
    %table{class: "table table-hover"}
      %thead
        %tr
          %th Name
          %th Prerequisites
          %th Benefit
      %tbody#rules
      -@rules.each do |rule|
        %tr{id: "#{rule.id}", onclick: "show_content(this);"}
          %td= rule.name
          %td= rule.data["PrintPrereq"]
          %td= rule.data["ShortDescription"]
  #rule_panel{class: "col-md-3"}
    -if @rules.first
      .panel.panel-default#rule_data{'data-spy': "affix"}
        .panel-heading
          %h3.panel-title Feat
        .panel-body
          %strong Name:
          %span#rule_name= @rules.first.name
          %br
          %strong Prerequisites:
          %span#rule_prereqs= @rules.first.data['PrintPrereq']
          %br
          %strong Benefit:
          %span#rule_content= @rules.first.content.html_safe